---
- hosts: all
  become: yes
  gather_facts: yes
  vars: 
   user_name: martin22
   collor: red


  tasks: 
     - name: install passwd package
       apt: 
         name: passwd
         state: present
       when: ansible_distribution in "Debian, Ubuntu"
       tags:
         -app1
      
     - name: create group
       group:
         name: cloudteam
         state: present
 #      when: ansible_distribution_major_version <9
     - name: create user
       user: 
         name: "{user_name}"
         comment: martin admin
         group: cloudteam
- hosts: db
  become: yes
  tasks:
    - name: install aapaache
      apt: 
       name: apache2
       state: present         
    - name: start apache2 service
      service: name=apache2 state=started enabled=yes 
      tags: 
       - services
    - name: copy index file
      copy:
       src: index.html
       dest: /var/www/html/index.html
       mode: 0644
    